[pytest]
python_files = \*abc.py
[pytest]
markers =
    positive: marks tests as positive (these tests should pass with valid input)
    negative: marks tests as negative (these tests should pass with invalid or edge-case input)

